//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CanBo_ThanNhan
    {
        public int Ma_CanBo_ThanNhan { get; set; }
        public int Ma_CanBo { get; set; }
        public string HoTen { get; set; }
        public string DoB { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string SoCCCD { get; set; }
        public string NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string VaiTroThanNhan { get; set; }
        public string NgheNghiep { get; set; }
        public string NoiLamViec { get; set; }
    }
}
