//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CoQuanDonVi
    {
        public int Ma_CoQuan_DonVi { get; set; }
        public string Ten { get; set; }
        public Nullable<int> MaLoai_CoQuan_DonVi { get; set; }
    }
}
