//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_ChiTietPhanQuyen
    {
        public int ID { get; set; }
        public string ChucNangCode { get; set; }
        public string MaTaiKhoan { get; set; }
        public string MenuCode { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
