//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_DanhSachMenu
    {
        public int ID { get; set; }
        public string KeyMenu { get; set; }
        public string MenuName { get; set; }
        public string Title { get; set; }
        public string MenuNameAlias { get; set; }
        public string MenuNameContent { get; set; }
        public string PageKey { get; set; }
        public string Alignment { get; set; }
        public Nullable<int> MenuType { get; set; }
        public Nullable<int> IsGroup { get; set; }
        public string Module { get; set; }
        public string PathIcon { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsBold { get; set; }
        public string KeyWork { get; set; }
        public string SorOrder { get; set; }
    }
}
