//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_PQCN
    {
        public int ID { get; set; }
        public int Ma_Menu { get; set; }
        public int Ma_ChucNang { get; set; }
        public string Ma_Role { get; set; }
        public bool TrangThai { get; set; }
    }
}
