//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_TaiKhoan
    {
        public int ID { get; set; }
        public int Ma_CanBo { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> MaNhomTaiKhoan { get; set; }
        public string TenNhomTaiKhoan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string MaTaiKhoan { get; set; }
        public string Code { get; set; }
        public string Email { get; set; }
        public Nullable<bool> CheckPass { get; set; }
    }
}
