//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_CapTaiKhoan
    {
        public int ID { get; set; }
        public Nullable<int> NguoiGui { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<int> NguoiCap { get; set; }
        public string FileCap { get; set; }
    }
}
