//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_KeKhai_TaiKhoanNuocNgoai
    {
        public int Ma_KeKhai_TSTN { get; set; }
        public int Ma_TaiKhoanNuocNgoai { get; set; }
        public string TenChuTaiKhoan { get; set; }
        public string TenNganHang { get; set; }
        public string SoTaiKhoan { get; set; }
    }
}
