//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_KeKhai_QuyenSuDungDat
    {
        public int Ma_QuyenSuDungDat { get; set; }
        public int Ma_KeKhai_TSTN { get; set; }
        public string TenLoaiDat { get; set; }
        public string DiaChi { get; set; }
        public string DienTich { get; set; }
        public string GiaTri { get; set; }
        public string GiayChungNhan { get; set; }
        public string ThongTinKhac { get; set; }
        public string LoaiDat { get; set; }
    }
}
