//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_KeKhai_TSTN_CanBoThanNhan
    {
        public int Ma_KeKhai_TSTN_CanBo_ThanNhan { get; set; }
        public Nullable<int> Ma_KeKhai_TSTN { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string SoCCCD { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string VaiTroThanNhan { get; set; }
        public string NgheNghiep { get; set; }
        public string NoiLamViec { get; set; }
    }
}
