//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_KeKhai_BienDongTaiSan
    {
        public int Ma_BienDongTaiSan { get; set; }
        public int Ma_KeKhai_TSTN { get; set; }
        public string LoaiTSTN { get; set; }
        public string TenLoaiTSTNJson { get; set; }
        public string SoLuongTaiSanJson { get; set; }
        public string GiaTriTSTNJson { get; set; }
        public string NoiDungGiaiTrinhJson { get; set; }
    }
}
