//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_KeKhai_TongThuNhap
    {
        public int Ma_TongThuNhap { get; set; }
        public Nullable<int> Ma_KeKhai_TSTN { get; set; }
        public string TongThuNhap_NguoiKeKhai { get; set; }
        public string TongThuNhap_VoHoacChong { get; set; }
        public string TongThuNhap_ConChuaThanhNien { get; set; }
        public string TongThuNhap_CacKhoanChung { get; set; }
    }
}
