//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nv_KeKhai_TSTN
    {
        public int Ma_KeKhai_TSTN { get; set; }
        public Nullable<int> Ma_CanBo { get; set; }
        public Nullable<short> Ngay_KeKhai { get; set; }
        public Nullable<short> Thang_KeKhai { get; set; }
        public Nullable<short> Nam_KeKhai { get; set; }
        public Nullable<System.DateTime> NgayThangNam { get; set; }
        public Nullable<int> Ma_Loai_KeKhai { get; set; }
        public Nullable<int> Ma_LinhVuc_KeKhai { get; set; }
        public Nullable<int> MaKeHoachKeKhai { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string FileDinhKem { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string SoCCCD { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public Nullable<int> Ma_CoQuan_DonVi { get; set; }
        public Nullable<int> Ma_ChucVu_ChucDanh { get; set; }
        public string BienDongTaiSan { get; set; }
        public Nullable<int> TrangThaiTiepNhan { get; set; }
        public string FileKiXacNhan { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
    }
}
