//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh_KetLuanXacMinh
    {
        public int ID_KetLuanXacMinh { get; set; }
        public Nullable<int> ID_KeHoachXacMinh { get; set; }
        public string SoKetLuan { get; set; }
        public string NgayKetLuan { get; set; }
        public string NoiDungKetLuan { get; set; }
        public string FileKetLuan { get; set; }
    }
}
