//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh_DanhSachCanBoXacMinh
    {
        public int ID_DanhSach { get; set; }
        public string TenDanhSach { get; set; }
        public Nullable<int> KeHoachNam { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLapDanhSach { get; set; }
    }
}
