//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh_DanhSachCanBoXacMinh_ChiTiet
    {
        public int ID_ChiTiet { get; set; }
        public Nullable<int> ID_DanhSach { get; set; }
        public Nullable<int> Ma_CanBo { get; set; }
    }
}
