//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachKeKhai_DanhSachKeKhaiBoNhiemCongTacCanBo
    {
        public int MaKeHoachKeKhai_DanhSachKeKhaiBoNhiemCongTacCanBo_ID { get; set; }
        public Nullable<int> MaKeHoachKeKhai { get; set; }
        public Nullable<int> Ma_CoQuan_DonVi { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
