//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh_BaoCaoKetQuaXacMinh
    {
        public int ID_BaoCaoKetQuaXacMinh { get; set; }
        public Nullable<int> ID_KeHoachXacMinh { get; set; }
        public string SoBaoCao { get; set; }
        public string NgayBaoCao { get; set; }
        public string FileBaoCao { get; set; }
    }
}
