//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachKeKhai
    {
        public int MaKeHoachKeKhai { get; set; }
        public string TenKeHoachKeKhai { get; set; }
        public Nullable<int> KeHoachNam { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string TienDo { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauCongKhai { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThucCongKhai { get; set; }
        public Nullable<int> Ma_Loai_KeKhai { get; set; }
        public Nullable<int> Ma_CoQuan_DonVi { get; set; }
        public string NguoiTao { get; set; }
        public string NghiDinh { get; set; }
    }
}
