//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh_GuiVaCongKhaiKetLuanXacMinh
    {
        public int ID_GuiVaCongKhaiKetLuanXacMinh { get; set; }
        public Nullable<int> ID_KeHoachXacMinh { get; set; }
        public Nullable<System.DateTime> NgayCongKhaiKetLuan { get; set; }
        public string NoiDungBienBan { get; set; }
        public string FileBienBan { get; set; }
    }
}
