//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh_RaQuyetDinhXacMinh
    {
        public int ID_RaQuyetDinhXacMinh { get; set; }
        public Nullable<int> ID_KeHoachXacMinh { get; set; }
        public string SoVanBan { get; set; }
        public Nullable<System.DateTime> NgayLapVanBan { get; set; }
        public string NoiDungVanBan { get; set; }
        public string FileVanBan { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
        public string CanCuBanHanhQuyetDinhXacMinh { get; set; }
        public string FileToXacMinh { get; set; }
        public string FileDanhSachCanBoXacMinh { get; set; }
        public string NoiDungXacMinh { get; set; }
        public Nullable<int> ThoiHanXacMinh { get; set; }
        public string FileNhiemVuQuyenHan { get; set; }
        public string FileCoQuanToChucPhoiHop { get; set; }
        public string FileQuyetDinh { get; set; }
    }
}
