//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LapKeHoachXacMinh
    {
        public int ID_KeHoach { get; set; }
        public string SoKeHoach { get; set; }
        public Nullable<System.DateTime> NgayLapKeHoach { get; set; }
        public string NoiDungKeHoach { get; set; }
        public Nullable<int> ID_DanhSachCanBo { get; set; }
        public string FileKeHoach { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> TienDo { get; set; }
        public Nullable<bool> TrangThai_ChinhSua { get; set; }
    }
}
